# Generated by Django 5.2.6 on 2026-02-26 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poblacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carretera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Tramo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_inicio', models.FloatField()),
                ('km_fin', models.FloatField()),
                ('tipo_final', models.CharField(choices=[('F', 'Físico'), ('C', 'Confluencia'), ('N', 'Ninguno')], default='N', max_length=1)),
                ('carretera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramos', to='gestion.carretera')),
                ('confluye_con', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recibe_confluencia', to='gestion.carretera')),
                ('pueblo_fin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fin_tramos', to='gestion.poblacion')),
                ('pueblo_inicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inicio_tramos', to='gestion.poblacion')),
            ],
        ),
    ]
